export const FormActions: State.ActionTypes = {
  REMOVE_DOCUMENT_ERROR: "REMOVE_DOCUMENT_ERROR",
  EXITED_NESTED_FORM: "EXITED_NESTED_FORM",
  EXITED_FORM: "EXITED_FORM",
  SET_REQUIRED_NESTED: "SET_REQUIRED_NESTED",
  RESET_FORM: "RESET_FORM",
  CLEAR_FORM_STATUS: "CLEAR_FORM_STATUS",
  DOCUMENT_SAVED: "DOCUMENT_SAVED",
  ADD_FORM_DATA: "ADD_FORM_DATA",
  ADD_ENTRY: "ADD_ENTRY",
  DELETE_ENTRY: "DELETE_ENTRY",
  UPDATE_ENTRY_ERRORS: "UPDATE_ENTRY_ERRORS",
  RESET_ENTRY: "RESET_ENTRY",
  CACHE_FORM_DATA: "CACHE_FORM_DATA",
  RESTORE_CACHED_FORM_DATA: "RESTORE_CACHED_FORM_DATA",
  ADD_INCIDENT: "ADD_INCIDENT",
  ADD_DOCUMENT_ERROR: "ADD_DOCUMENT_ERROR",
  SHOWING_FORM_ERRORS: "SHOWING_FORM_ERRORS",
};

export const FormStatus: { readonly [S in ScribePro.FormStatus]: S } = {
  EMPTY: "EMPTY",
  COMPLETE: "COMPLETE",

  SHOW_ERRORS: "SHOW_ERRORS",
  DOCUMENT_SAVED: "DOCUMENT_SAVED",
  EXIT_NESTED: "EXIT_NESTED",
  EXIT: "EXIT",
};
